name: VELQIX
description: VELQIX - Plateforme de location et vente de biens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.6

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  http: ^1.1.0
  http_parser: ^4.0.0

  # Auth sociale
  google_sign_in: ^6.2.0
  flutter_facebook_auth: ^7.0.1

  # URL Launcher
  url_launcher: ^6.3.0

  # Reconnaissance vocale
  speech_to_text: ^7.0.0

  # Sélection image/vidéo natif Android/iOS
  image_picker: ^1.1.2

  # Appels VoIP in-app via Agora
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  
  socket_io_client: ^2.0.3+1   # pour mobile uniquement
  record: ^6.2.1
  audioplayers: ^6.7.1
  path_provider: ^2.1.6
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  flutter_local_notifications: ^22.3.1
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png